[workspace]
members = [
	"0_gcd",
	"1_iron-gcd",
	"2_mandelbrot",
	"3_generic-queue",
	"4_complex",
	"5_basic-router",
	"6_binary-tree",
	"7_grep",
	"8_copy",
	"9_echo-server",
	"10_http-get",
	"11_json-macro",
]